apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-flask-app
  namespace: postgres-db
  labels:
    app: cve-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cve-flask-app
  template:
    metadata:
      labels:
        app: cve-flask-app
    spec:
      containers:
      - name: cve-flask-app
        image: burnata/postgres-db-cve-forms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: cve-flask-app-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: cve-flask-app-secret
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cve-flask-app-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cve-flask-app-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cve-flask-app-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: ssl-cert
          mountPath: "/etc/ssl/certs"
          readOnly: true
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
      volumes:
      - name: ssl-cert
        secret:
          secretName: cve-flask-app-secret
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key